SecuringDataHosting/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('Upload.urls')),
    path('accounts/',include ('accounts.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Upload/urls.py
from django.urls import path
from .views import DocumentCreateView, DocumentListView, download
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', DocumentListView.as_view(), name='home'),
    path('upload/', login_required(DocumentCreateView.as_view()), name='upload'),
    path('download/<int:document_id>/', login_required(download), name='download'),
]

accounts/urls.py
from django.urls import path
from .views import login,signup,logout
urlpatterns = [
    
    path('login/',login,name="login"),
    path('signup/',signup,name="signup"),
    path('logout/',logout,name="logout"),
]

Upload/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.db import models
from .AES import encrypt,getKey,encrypt_file
class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document    = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    user        = models.ForeignKey(User, verbose_name="User",null=True, on_delete=models.CASCADE)
    def save(self, *args, **kwargs):
        print("file name:",(self.document.file.name))
       
        super(Document, self).save(*args, **kwargs)
        self.document = open(encrypt(getKey(self.user.password), self.document.file.name))

accounts/models.py
from django.db import models

# Create your models here.

Upload/forms.py
from django import forms
from .models import Document
from django.contrib.auth.models import User
class DocumentForm(forms.ModelForm):
    # user = forms.CharField(widget=forms.TextInput(attrs={'type':'hidden','value':}))
    class Meta:
        model = Document
        fields = ('description', 'document')

Upload/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .models import Document
from .forms import DocumentForm
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.views.generic import ListView
# from .models import Document

from .AES import decrypt,getKey,decrypt_file


class DocumentListView(LoginRequiredMixin,ListView):
    login_url = '/accounts/login/'
    model = Document
    template_name = 'documents.html'
    context_object_name = 'documents'

class DocumentCreateView(CreateView):
    model = Document
    form_class = DocumentForm
    template_name = 'upload.html'
    success_url = reverse_lazy('home')
    
    def getInstance(self):
        return Document.objects.filter(user_id=self.request.user.id)    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.getInstance()
        print(context)
        user = self.request.user
        context["user"] = User.objects.get(id=user.id)
        return context
    def get_form_kwargs(self):
        kwargs = super(DocumentCreateView, self).get_form_kwargs()
        
        if kwargs['instance'] is None:
            kwargs['instance'] = Document()
        user = self.request.user
        user= User.objects.get(id=user.id)
        # form.instance.user = user
        kwargs['instance'].user = user
        print(kwargs)
        return kwargs
    # def form_valid(self, form):
    #     # This method is called when valid form data has been POSTed.
    #     # It should return an HttpResponse.
    #     print("d----------------------------",dir(form))
    #     user = self.request.user
    #     user= User.objects.get(id=user.id)
    #     form.instance.user = user
    #     return super().form_valid(form)


from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from .models import Document

def download(request, document_id):
    document = get_object_or_404(Document, pk=document_id)
    # decrypt(getKey(document.user.password),document.document.file.name)
    response = HttpResponse(document.document, content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{document.document.file.name}"'
    return response

accounts/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib import auth

def signup(request):
    if request.method == "POST":
        if request.POST['password1'] == request.POST['password2']:
            try:
                User.objects.get(username = request.POST['username'])
                return render (request,'accounts/signup.html', {'error':'Username is already taken!'})
            except User.DoesNotExist:
                user = User.objects.create_user(request.POST['username'],password=request.POST['password1'])
                auth.login(request,user)
                return redirect('home')
        else:
            return render (request,'accounts/signup.html', {'error':'Password does not match!'})
    else:
        return render(request,'accounts/signup.html')

def login(request):
    if request.method == 'POST':
        user = auth.authenticate(username=request.POST['username'],password = request.POST['password'])
        if user is not None:
            auth.login(request,user)
            return redirect('home')
        else:
            return render (request,'accounts/login.html', {'error':'Username or password is incorrect!'})
    else:
        return render(request,'accounts/login.html')

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
    return redirect('login')

templates/accounts/accounts.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

   <style>
    html,body { 
      height: 100%; 
    }
    
    .global-container{
      height:100%;
      display: flex;
      align-items: center;
      justify-content: center;
      background-color: #f5f5f5;
    }
    
    form{
      padding-top: 10px;
      font-size: 14px;
      margin-top: 30px;
    }
    
    .card-title{ font-weight:300; }
    
    .btn{
      font-size: 14px;
      margin-top:20px;
    }
    
    
    .login-form{ 
      width:330px;
      margin:20px;
    }
    
    .sign-up{
      text-align:center;
      padding:20px 0 0;
    }
    
    .alert{
      margin-bottom:-30px;
      font-size: 13px;
      margin-top:20px;
    }
   </style>
  <title>تأمين وتخزين البيانات في الإستطافات السحابية</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>

<body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href=""></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      </div>
    </nav>
  </header>
  <div class="global-container">
    <div class="card login-form">
    <div class="card-body">

      {% block content %}
      {% endblock %}
  </div>

  <footer class="text-muted">
    <div class="container text-center">
      <p>This is a footer {% now "Y" %}</p>
      </div>
  </footer>

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

</code></pre>

templates/accounts/login.html
{% extends 'accounts/accounts.html' %}
{% comment %} {%load static%} {% endcomment %}
{% block content %}


{% if error %}
{{ error }}

<br/>
<br/>
{% endif %}

<h1>Login!</h1>

<form method = "POST" action="{% url 'login' %}">
    {% csrf_token %}
    username:
    <br/>
    <input type="text" name="username" />
    <br/>
    Password:
    <br/>
    <input type="password" name="password" />
   
    <br/>
    <br/>
    <input class ="btn btn-primary" type="submit" value= "Login" />
    
    <br/>
     I have not account <a class =" "  type="button" href="/accounts/signup/">register</a>


</form>


{% endblock %}

templates/accounts/signup.html
{% extends 'accounts/accounts.html' %}

{% block content %}


{% if error %}
{{ error }}

<br/>
<br/>
{% endif %}

<h1>Signup!</h1>

<form method = "POST" action="{% url 'signup' %}">
    {% csrf_token %}
    username:
    <br/>
    <input type="text" name="username" />
    <br/>
    Password:
    <br/>
    <input type="password" name="password1" />
    <br/>
    confirm Password:
    <br/>
    <input type="password" name="password2" />
    <br/>
    <input class ="btn btn-primary" type="submit" value= "signup" />
    {% comment %} <input value=""{%request.user%}}" name="user" type="hidden"> {% endcomment %}
    <br/>
   already Ihave account <a class =""  type="button" href="/accounts/login/">login</a>



</form>


{% endblock %}

templates/base.html
{% load static %}
{% if request}
<!DOCTYPE html>
<html lang="ar" dir="rtl">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>تأمين وتخزين البيانات في الإستطافات السحابية</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin - v2.2.2
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body dir="rtl">

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center" dir="ltr">

    <div class="d-flex align-items-center justify-content-between">
      <a href="index.html" class="logo d-flex align-items-center">
        <img src="assets/img/logo.png" alt="">
        <span class="d-none d-lg-block"></span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

        

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="{% static 'assets/img/profile-img.jpg' %}" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2"> {{request.user.username}}  </span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6> {{request.user.username}} </h6>
              {% comment %} <span>مطور ويب</span> {% endcomment %}
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                <i class="bi bi-question-circle"></i>
                <span>Need Help?</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="/accounts/logout/">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar" dir="rtl" style="direction:ltr;">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link " href="index.html">
          <i class="bi bi-grid"></i>
          <span>لوحة القيادة</span>
        </a>
      </li><!-- End Dashboard Nav -->

      
    </ul>

  </aside><!-- End Sidebar-->

  <main id="main" class="main" dir="rtl">

    <div class="pagetitle">
      <h1>لوحة القيادة</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">الرئيسية</a></li>
          <li class="breadcrumb-item active">لوحة القيادة</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
      <div class="row">
         {% block content%}
        <!-- Left side columns -->
        <div class="col-lg-12">
          <div class="row">

            <!-- Sales Card -->
            <div class="col-xxl-4 col-md-6">
              <div class="card info-card sales-card">

                <div class="filter">
                  <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                  <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                    <li class="dropdown-header text-start">
                      <h6>Filter</h6>
                    </li>

                    <li><a class="dropdown-item" href="#">Today</a></li>
                    <li><a class="dropdown-item" href="#">This Month</a></li>
                    <li><a class="dropdown-item" href="#">This Year</a></li>
                  </ul>
                </div>

                <div class="card-body">
                  <h5 class="card-title">Sales <span>| Today</span></h5>

                  <div class="d-flex align-items-center">
                    <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                      <i class="bi bi-cart"></i>
                    </div>
                    <div class="ps-3">
                      <h6>145</h6>
                      <span class="text-success small pt-1 fw-bold">12%</span> <span class="text-muted small pt-2 ps-1">increase</span>

                    </div>
                  </div>
                </div>

              </div>
            </div><!-- End Sales Card -->

            <!-- Revenue Card -->
            <div class="col-xxl-4 col-md-6">
              <div class="card info-card revenue-card">

                <div class="filter">
                  <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                  <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                    <li class="dropdown-header text-start">
                      <h6>Filter</h6>
                    </li>

                    <li><a class="dropdown-item" href="#">Today</a></li>
                    <li><a class="dropdown-item" href="#">This Month</a></li>
                    <li><a class="dropdown-item" href="#">This Year</a></li>
                  </ul>
                </div>

                <div class="card-body">
                  <h5 class="card-title">Revenue <span>| This Month</span></h5>

                  <div class="d-flex align-items-center">
                    <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                      <i class="bi bi-currency-dollar"></i>
                    </div>
                    <div class="ps-3">
                      <h6>$3,264</h6>
                      <span class="text-success small pt-1 fw-bold">8%</span> <span class="text-muted small pt-2 ps-1">increase</span>

                    </div>
                  </div>
                </div>

              </div>
            </div><!-- End Revenue Card -->

            <!-- Customers Card -->
            <div class="col-xxl-4 col-xl-12">

              <div class="card info-card customers-card">

                <div class="filter">
                  <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                  <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                    <li class="dropdown-header text-start">
                      <h6>Filter</h6>
                    </li>

                    <li><a class="dropdown-item" href="#">Today</a></li>
                    <li><a class="dropdown-item" href="#">This Month</a></li>
                    <li><a class="dropdown-item" href="#">This Year</a></li>
                  </ul>
                </div>

                <div class="card-body">
                  <h5 class="card-title">Customers <span>| This Year</span></h5>

                  <div class="d-flex align-items-center">
                    <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                      <i class="bi bi-people"></i>
                    </div>
                    <div class="ps-3">
                      <h6>1244</h6>
                      <span class="text-danger small pt-1 fw-bold">12%</span> <span class="text-muted small pt-2 ps-1">decrease</span>

                    </div>
                  </div>

                </div>
              </div>

            </div><!-- End Customers Card -->


          </div>
        </div><!-- End Left side columns -->

       {%endblock%}

      </div>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/chart.js/chart.min.js' %}"></script>
  <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/quill/quill.min.js' %}"></script>
  <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/documents.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <h2>Documents</h2>
  <ul>
    {% for document in documents %}
       {% if document.user.id == request.user.id%}
            <li>
                {{ document.description }} - 
                <a href="{% url 'download' document.id %}">Download</a>
            </li>
        {% comment %} {% elif %} {% endcomment %}
        {% endif %}   
       {%  empty %}
      <li>No documents found.</li>
    {% endfor %}
  </ul>
<a href="/upload/">Upload new Documents</a>

{% endblock %}

templates/upload.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <h2>Upload a file</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input value="{{request.user}}" name="user" id="user" type="hidden"/>
    {% comment %} <input type="hidden" name="csrfmiddlewaretoken" value="54RsezR0uGpmnrz8UVbiaNuEN1l5QKMQ0vBarPZuYDPGdBOL2OSTD6paWM9fkd0y"> {% endcomment %}
    {% comment %} <input value="mohemmedkamal0115498898@gmail.com" name="user" id="user" type="hidden"/> {% endcomment %}
    <p>
    <label for="id_description">Description:</label>
    <input type="text" name="description" maxlength="255" id="id_description">
    </p>
     <p>
    <label for="id_document">Document:</label>
    <input type="file" name="document" required id="id_document">
      {% comment %} <input type="hidden" name="user" id="id_user"> {% endcomment %}
    
  </p>
    <button type="submit">Upload</button>

  </form>
{% endblock %}